### ISSUE TITLE
dbEdit/institutions, setting load does not work

### ISSUE THREAD

**Issue by maxfl** [basil-g/juno#10]
In Beijing it was not possible to set and save the institution load in dbEdit/institutions page.

Now, I've tried changing JINR load for 2019 and have succeeded.

@ZhiminWangIHEP, please confirm, that the issue is still valid, or not.

**Comment by ZhiminWangIHEP** [comment]
Yes,
I just tested with IHEP as example for 2018, it works.
Thanks
