### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by maxfl** [basil-g/juno#11]
Could we show a meassage or warning for January 2019 in round 2018: like exceed the range of round for signup? or other kind?

_Originally posted by @ZhiminWangIHEP in https://github.com/basil-g/juno/issues/9#issuecomment-443088506_

**Comment by basil-g** [comment]
ok, I'll do it

**Comment by basil-g** [comment]
@ZhiminWangIHEP
Done and checked. The shift dates are checked for a selected round (date-from .. date-upto)
Please doublecheck if it's OK

**Comment by ZhiminWangIHEP** [comment]
@basil-g seems no change for me, any wrong with me?

**Comment by ZhiminWangIHEP** [comment]
![image](https://user-images.githubusercontent.com/44493684/49552474-cbee3d00-f92e-11e8-8cfa-e0befc245c0d.png)
Here is the screen shot from my test.

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
When a person attempts to book a shift for 2019 using "PMT shift year 2018" - one would be rejexted and advised to select and use the next round.
"PMT shift year 2018" - must be closed by a shift manager when there should be no more booking for the round or when the round expires.

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Close the issue please if solved

**Comment by ZhiminWangIHEP** [comment]
I See.
I didn't test, but I think it works.
let me close it. thanks

**Comment by ZhiminWangIHEP** [comment]
sorry, we need ask Maxim to close it.
@maxfl
