### ISSUE TITLE
An expert shifter could not signup as a chief shifter by himself

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#12]
@basil-g 
An new expert shifter could not signup by himself as a chief shifter, as shown on his screen shoot.
While I can do it for him.
His name is Anqing Wang, from Shandong University.
Any problem to him?
Thanks,
<img width="1257" alt="capture_cran 2018-12-05 a_ 20 22 58" src="https://user-images.githubusercontent.com/44493684/49552454-ad884180-f92e-11e8-959a-d3457e63f22f.png">

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
I'll check it up

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Close the issue please if solved

**Comment by ZhiminWangIHEP** [comment]
sure
