### ISSUE TITLE
Signup with unit of weeks

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#13]
@basil-g 
There has another issues with the current signup system:
it is better to limit the shifter to signup with the period of # weeks, is it possible to add this limitation in the system?
if there has any confliction on holiday with this rule, can be changed.
Thanks

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
You mean to add a restriction forbidding a person to book shifts if

book_date - today < #weeks x 7 ?

Yes, of course that may be done.
Just specify the number of weeks.
And sure there would be no such limitation for administrators.

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Sorry again for the missed notification on thiss item.

The issue is that we hope the shifters to sign folloing the rules with whole weeks rather than days, which is better for shifter arrangement and calculation, while I know there should have related issues for holidays.
What's your seggestions?
