### ISSUE TITLE
Statistics - add a new filter

### ISSUE THREAD

**Issue by basil-g** [basil-g/juno#15]
<Zhimin, please put desired items separately, but not within a discussion body. I've done it for you>
"I ask you to label the entries for Chinese and not Chinese institutes, that is ok?"

**Comment by basil-g** [comment]
@ZhiminWangIHEP
I've added an additional filter on the statistics page - please have a look.
It's available for shifts managers and admins.
"filt: all / China/ not China"
So you may separate the statistics for chinese and foreign participants if you wish.

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Yes, I saw and Tested, it works well, great.
