### ISSUE TITLE
Please display the system experts also

### ISSUE THREAD

**Issue by weiswang** [basil-g/juno#16]
There are two PMT testing systems at the Pan-Asia site:

1. Container System
2. Scanning Station

Each shall have one expert operating them. But they don't accept free sign-up. Their operators'/experts' names are put down by Bjoern and Nikolay only. Please implement this and open the right to sign up only to Bjoern and Nikolay.

The Container System's operator/expert is decided by Bjoern, discussing with other L2's and L3's if necessary.

The Scanning Station's operator/expert is decided by Nikolay, discussing with other L2's and L3's if necessary.

The reason is twofold: 1. we need to know; 2. other close collaborators, if they want to work with particular experts, could see the information.

Thanks.

**Comment by basil-g** [comment]
@weiswang 
Don't actually get what I am to "implement" within the current "Shift System"
Please specify the task looking at presently available functions and interface (menu of operations, screens,etc)
