### ISSUE TITLE
Automatic Reminder for signed shifter and manually reminder for signup of each institute?

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#17]
@basil-g 
Dear Basil,
Do you think it is possible to add some reminder to the system, for example:
1. automatic reminder the signed shifter to prepare their signed shifter, for example 1 week before their date.
2. manual send out some email to remind each institute responser (espacially not full signed institutes) to check/sign their remain shifts?
THank you

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Yes
This feature is written already in code according to the very first requirements set (long ago) but was not  switched on yet. It would be surely done, when you have the system work for you exactly the way you need it to.
