### ISSUE TITLE
Wrong institute name correction

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#18]
@basil-g 
There has one institute name is wrong, while I didn't  find a way to correct, could you help?
The wrong one (on the current insistute list, also one signed shifter in 2018 with it): 
full name: |  Department of Nuclear Physics
short name (abbreviation): |  DNP-FMPH-UNIBA
country: |  Slovakia
* | address: |  Bratislava, Slovakia
* | representative: |  Andrej Babic

while the right one (which also on the current list):
full name: |  Comenius University Bratislava, Faculty of Mathematics, Physics and Informatics
short name (abbreviation): |  FMFI-UK
country: |  Slovakia
* | address: |  Bratislava, Slovakia
* | representative: |  Andrej Babic

Thanks

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
I've removed the wrong institution (Department of Nuclear Physics, DNP-FMPH-UNIBA)
and corrected the shifts.
BUT,  now there are 2 persons in Comenius University Bratislava
Andrej Babic and Andrej BABIC
I don't know which one is actual - that's for you to decide and remove.
Just delete one in dbedit->users (select Comenius... and you'll see the cloned person and one more)

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Thank you very much.
I removed the "Andrej BABIC"

And I will close this ticket.
