### ISSUE TITLE
Add new columns on the daily shiters' list

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#20]
@basil-g 
Dear Basil,
According to last night JUNO IB discussion, there have few new requirements to our shifter system, I just list here, could you help to modify/updpate the system?
(Nikolay also will discuss with you when he back to Dubna)
1.  add another two experts to the current shifter list, means:
    1 chief shifter (expert)
    1 station expert shifter (expert)
    1. container shifter (expert)
    3 normal shifters (normal shifter)
   (and all the expert shifters have a weight 1.1, normal shifter weight 1)
2.  Block the experts
   Pease block the two expert region before further information by the following name, then, I will ask the guys to edit/sign to the expert
    1 station expert==> in default blocked to JINR or Nikolay
    1 container expert ==> in default blocked to German or Tobias L.
3.   Update the statistics
    According to the update, we also need to update the statistics.
    But for this update, I think we still need to discuss to finalize about the format.
     (for example, points in weeks, shifter weeks, expert weeks, chief shifter weeks)

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Just to be sure I've got you right. 
1 Do I have to add 2 more experts - that would sum up to 6 person per a shift:

1 cheif shifter (expert - 1.5 points/per shift)
2 NEW! station expert shifter (expert - 1.1)
3 NEW! container shifter (expert - 1.1)
4 normal shifter (1.0)
5 normal shifter (1.0)
6 normal shifter (1.0)

2. I get it - Nikolay has explained me the idea.
3.  Statistics. I see you need to change the format, but it may be done only after all of the planned changes take place.

Zhimin, and what's the deadline for items 1 and 2?
As soon as 2 entities are to be added - that would influence all of the internals of the system.
That should be done with all the precautions not to crash everything )).

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
for the 1: Do I have to add 2 more experts - that would sum up to 6 person per a shift:
1 cheif shifter (expert - 1.5 points/per shift)  also should modify to 1.1 points/per shift

for 3. statistics, I agree with you. Plan do that as you plan and checked.

Zhimin, and what's the deadline for items 1 and 2?
==> this one should be as earlier as possible.
While as you know, Chinese New year is coming: Feb 4 to Feb 10. Chinese side response will be delayed.

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
I've changed 1.5 points pers hshift for a chief expert to 1.1 point.
But note, that all of the shifts booked before today (29-Jan-2019) would stay with 1.5 and spoil your statistics. 
Q: Should I change "manually" (in the dB) expert chief shifts for at least this year from 1.5 to 1.1?

Station and container expert shifts implementation and testing would take some time: 
lots of small to average changes througout the whole code are to be made. I'll do my best.

**Comment by ZhiminWangIHEP** [comment]
@basil-g
Thank you. 
For 2019,  if it  is possible, I think it is better to modify all of them to 1.1 points for final statistics.

The others, I think it is fine,
Happy Chinese new year. 
Best,

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
I've changed all of the chief shifts with 1.5 points to 1.1 for 2019.
Now proceeding with the station and container expert shifts implementation.

Happy new year, and have a good time!

Cheers

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Good, thanks.
Happy Chinese New year to you too.

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Dear Zhimin
I've resolved the issue
1. container and station shifts added for expert-skill persons
2. the following persons would be able to assign them:
Zhimin W, Anfimov N, Tobias L,  ( Gromov B - me - just for emergency cases)
The list is hardcoded and tied to the system user account ID. 
But can be easily edited if need arises.
3. 1.1 point is assigned per shift
4. the shift type is selected via the checkboxes next to the Submit button
No checkbox mark means type=common shifter
5 Nikolay Anfimov told me that a shift chief may be simultaneously the station or container chief.
So, I've made it possible, and the person would have 1.1 + 1.1 points per shift then

Please have a look. Is it what you were after? Or should anything be changed?
I've tested book/unbook operation. Appears to work OK for me.
P.S. All the changes made - could be easily rolled back

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Thank you,
I just tested for the station/container experts shift for Jan/Feb/March, it works, for booking and unbooking.
While the station and container experts shifter each should only have 1.1 point, am I understand right?

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Our German colleague feedback about the current naming with "Chief" which make few misunderstanding, so could we modify the shifter Chief, station chief, container chief to shifter expert, station expert, container expert?
our better ideas?
Thank you,
ZHimin

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Thanks.
I was not sure how to name it. I'll do it just now.

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Done
Additionally I've improved the "last question" before the book\unbook operations to assure
an institute representative or you that a proper person is going to be assigned shifts.

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Yeah, I saw the updated webpage.
Thanks
