### ISSUE TITLE
combine the statistics for INFN 

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#21]
@basil-g 
Dear Basil, there has a new request about the INFN statistics, is it possible to combine the required and taken shifts for INFN including all their institutes with INFN tag?

At the same time, is it possible to add a history statistics from begining to now for each institute?
Best,
Zhimin

Here is the email from Gioacchino Ranucci to Wei:
From: Gioacchino Ranucci <gioacchino.ranucci@mi.infn.it>
Sent: Thursday, January 24, 2019 22:30
To: 'Wei Wang'
Cc: 'Fabio Mantovani'; 'Gioacchino Ranucci'
Subject: shifts 2018
 
Dear Wei
In the 2018 shift table shown at the meeting it is written that INFN Milano did 4 weeks. In reality this 4 weeks were done 2 by INFN Milano and 2 by INFN Ferrara. This does not change the global INFN counting for 2018, but I would appreciate if you change the table accordingly.
The other option is to do what I asked last year, to list INFN in the shift table as a unique entity, without distinguishing the various branches.
In 2017 we as INFN did 6 shifts; do you consider also a global shift counting for all the years starting from 2017?  
Thanks
Best
Gioacchino

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
So the task would be
1) enable all the statistics available - for all periods totaly
2) enable the possibility to get statistics using literal tags for insitutions
Is that right?

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
1. yes.
2. this mainly used for INFN, which also only have one planed shifts.
thanks,

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Done
Have a look please, I've added a tag filter
You may use any keyword (say, INFN or university or .... whatever or any abbreviated name for a tag)
if round=all - that means all stats that we have

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
I checked that, the tag is working, while for INFN, shall we add their planed there?
