### ISSUE TITLE
New problem when signing 

### ISSUE THREAD

**Issue by ZhiminWangIHEP** [basil-g/juno#22]
@basil-g 
Dear Basil, this noon when I am trying to exteed the shifter for Safeer from April 1st to 6th, the system saied it is completed as attached, could you help to check?
(Before that, I just unbooked and booked for Huiling in this month )
Thank you
Best,
Zhimin

![image](https://user-images.githubusercontent.com/44493684/53856542-49e4e180-400d-11e9-9aa7-3cd6873cb611.png)

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Sorry, that was the side effect of adding station and container experts.
The problem is resolved.
Refresh the page with cash removal (Ctrl-F5) and try again, please

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Yeah, it is working now.
THank you, I will close this ticket.
